### ISSUE TITLE
Monitor criando arquivo tlpp.rpo

### ISSUE THREAD

**Issue by Redschenko** [totvs/tds-monitor-standalone#10]
Bom dia.

No meu ambiente utilizo balanceamento e tenho a configuração para atualização automática do smartclient.
Ao acessar este ambiente através do novo monitor, está sendo criado um arquivo chamado tlpp.rpo na pasta configurada como PATHWINDOWS no appserver.ini.
Com isto, constantemente o sistema solicita atualização do smartclient local para os usuários.

_**Dados do monitor**_
_TOTVS Monitor v0.2.1
@totvs/tds-languageclient: 0.0.21
@totvs/tds-monitor-frontend: 0.1.11_

Segue em anexo vídeo do problema.

[2020-09-03 09-19-29.zip](https://github.com/totvs/tds-monitor-standalone/files/5168462/2020-09-03.09-19-29.zip)

Aguardo solução.

At
Rodrigo de Oliveira

**Comment by Redschenko** [comment]
Atualizei o TDS Monitor, porém ainda continua o problema.

**_Dados do Monitor_**
TOTVS Monitor v0.2.2
@totvs/tds-languageclient: 0.0.22
@totvs/tds-monitor-frontend: 0.1.12

**Comment by Redschenko** [comment]
Conforme orientado pelo Ricardo Mansano (TOTVS), anexado o appserver.ini do meu ambiente.
No anexo, os arquivos appserver.ini foram renomeados para indicar onde cada um é utilizado.

[2009251210.zip](https://github.com/totvs/tds-monitor-standalone/files/5283573/2009251210.zip)

**Comment by lwtnb-wrk** [comment]
@Redschenko Qual a build exata do appserver que voce usa? Eu já vi esse tipo de ocorrencia no passado, mas nao consigo mais reproduzir.

**Comment by Redschenko** [comment]
@lwtnb-wrk 

_Build AppServer: 7.00.191205P-20200424 - 64 bits
Appserver version: 19.3.0.4_

**Comment by lwtnb-wrk** [comment]
@Redschenko Testei aqui nessa versão de AppServer indicada e não houve a criação do tlpp.rpo.
Pelo que entendo o tlpp.rpo está sendo distribuido com binario do appserver e se ele não existir o appserver cria um zerado.
Se possível atualize seu binário para uma versão mais atual e confirme que o arquivo tlpp.rpo já existe.
A principio o Monitor Electron não cria nenhum tipo de arquivo, ele apenas consome informação do AppServer, então essa criação de arquivo de qualquer forma vem do AppServer.
Não vejo nada que podemos fazer para evitar essa geração de arquivo.

**Comment by Redschenko** [comment]
@lwtnb-wrk 
Realizei a atualização do AppServer para a versão 19.3.0.6, porém o problema persiste.
Vi hoje que há uma nova versão do AppServer.
Vou planejar esta atualização em meu ambiente, depois realizar testes e acompanhamento.
Caso problema persista, vou abrir um chamado para a equipe do AppServer, fazendo referência a esta issue.

Estou fechando este caso.
Obrigado pela atenção.

**Comment by alcampos2007** [comment]
Boa tarde.
Isso foi resolvido ?
Qual a solução. (nosso ambiente está atualizado APPserver / smartcliente e está gerando o TLPP.RPO quando utilizamos o monitor electron).

**Comment by lwtnb-wrk** [comment]
@alcampos2007 Esse comportamento é do AppServer. O Monitor não tem nenhuma ação na criação do TLPP.RPO. Se isso for um problema, favor abrir um chamado com a equipe de AppServer.
