### ISSUE TITLE
Erro de conexão com build diferente

### ISSUE THREAD

**Issue by likid** [totvs/tds-monitor-standalone#11]
Ao configurarmos a conexão com um appserver, o monitor grava internamente a build do server onde se conectou, porém, se for feito uma atualização do sistema que envolva alterar a build do appserver, o monitor apenas gera erro de conexão ou solicita o ambiente novamente, sem a releitura da build, causando erros de conexão constantemente e forçando a excluir a configuração para incluir novamente.
Será necessário implementar a releitura da build ou a opção de selecionar a build ao configurar a conexão para que se possa corrigir esta alteração sem a necessidade de remover e incluir novamente.

**Comment by lwtnb-wrk** [comment]
@likid A ultima versão do Monitor Electron permite a edição dos servidores. 
Ao editar um servidor existente ele revalida as informações de build e secure, então ele deve pegar a nova build nesse caso.
Teste na ultima versão e veja se seu problema foi resolvido.

**Comment by likid** [comment]
@lwtnb-wrk fazendo a edição da conexão fez o monitor revalidar a build do server. Obrigado.
