### ISSUE TITLE
Alterar senha configurada no monitor

### ISSUE THREAD

**Issue by mateus-erp** [totvs/tds-monitor-standalone#18]
Bom dia, Pessoal.

Ao marcar a opção "Armazenar informações para reconexões automática" não conseguimos configurar outro usuário e senha do ambiente, com isso temos que deletar e criar um novo servidor.
Existe a possibilidade de implementação de uma nova funcionalidade que consiga alterar esses fatores sem a necessidade de criação de um novo servidor?

![image](https://user-images.githubusercontent.com/58174530/136385273-9eeae8c0-0b49-424b-80d7-1c5795609db3.png)

**Comment by brodao** [comment]
Se a conexão com token falhar, será solicitado nova identificação. Caso edite as configuração, o token será reinicializado.

Favor aguardar próxima liberação.

**Comment by lwtnb-wrk** [comment]
@marcos-abrahao Voce esta na ultima versao do Monitor Electron mesmo? Tivemos esse problema no passado, mas ja foi corrigido...
