### ISSUE TITLE
Sugestão de funcionalidade

### ISSUE THREAD

**Issue by likid** [totvs/tds-monitor-standalone#2]
Gostaria de sugerir a funcionalidade de exportação e importação das configurações de acesso aos servidores, pois no nosso ambiente possuímos muitos servidores e em caso de reinstalação do monitor ou instalação em outros computadores, é necessário recadastrar todos os servidores novamente. Com a funcionalidade de exportar e importar as configurações este trabalho tornaria-se muito mais simples.

**Comment by rogeriorc** [comment]
A partir da versao 0.2.0, o arquivo com as configurações é gravado em disco, podendo ser copiado para outras instalações.
Caminhos:
Windows: %APPDATA%\@totvs\tds-monitor-standalone\settings.json
Linux: ~/.@totvs/tds-monitor-standalone/settings.json
Mac: $HOME/Library/Preferences/@totvs/tds-monitor-standalone/settings.json
