### ISSUE TITLE
Coluna User Name ordenação

### ISSUE THREAD

**Issue by lucianovsjr** [totvs/tds-monitor-standalone#3]
As vezes preciso visualizar todas as execuções dos usuários, o único jeito é filtrar um a um. Teria como incluir a ordenação na coluna que contém o nome do usuário?

**Comment by gtrabach** [comment]
Boa tarde. A versão v0.1.4 do Monitor já possui essa melhoria.

**Comment by luisely** [comment]
Aonde esta o link para baixar essa versão? aqui só tem 0.0.11

**Comment by gtrabach** [comment]
Segue: https://suporte.totvs.com/portal/p/10098/download#all/all/all/search/MONITOR
