### ISSUE TITLE
Usuários com acentos

### ISSUE THREAD

**Issue by bernardoand** [totvs/tds-monitor-standalone#4]
Boa tarde,

Alguns usuários possuem acentos no user name, quando isso ocorre conseguimos visualizar suas conexões, mas não conseguimos desconecta-los(nada acontece ao clicar).

![image](https://user-images.githubusercontent.com/56555820/85433214-78683200-b55a-11ea-92cb-d3c53a717dff.png)

**Comment by rogeriorc** [comment]
Corrigido na versao 0.2.0
