### ISSUE TITLE
Coluna com a versão do SmartClient do usuário

### ISSUE THREAD

**Issue by gtrabach** [totvs/tds-monitor-standalone#5]
Gostaria de sugerir a inclusão de uma coluna onde informe qual a versão do SmartClient que o usuário está utilizando. 

Hoje já existe uma chamada Connection Type que exibe se o usuário está via remote Windows, Linux ou HTML. 

A ideia é que a nova coluna exiba dados como por exemplo: _7.00.191205P - 19.3.0.5_ ou _7.00.170117A - 17.3.0.14_ ou simplesmente _19.3.0.5_ ou _17.3.0.14_.

**Comment by lwtnb-wrk** [comment]
@gtrabach Esta sugestão deve ser requisitada ao time de AppServer da TOTVS.
O Monitor apenas exibe as informações fornecidas pelo AppServer.
Se esta mudança for aceita e o AppServer começar a retornar esta informação faremos os ajustes necessários.
