### ISSUE TITLE
⚠️ Problemas para monitorar usuários Cloud TOTVS

### ISSUE THREAD

**Issue by AlencarGabriel** [totvs/tds-monitor-standalone#7]
Olá, 

atualizei meu monitor para versão `0.1.4` disponível no Portal do Cliente, e o mesmo não está monitorando serviços de um ambiente hospedado no Cloud TOTVS.

Regredindo para versões anteriores funciona normalmente.

Estou anexando o LOG, não ocorre erros, mas também não retorna os usuários.

[LogErrorNewMonitor.log](https://github.com/totvs/tds-monitor-standalone/files/4960236/LogErrorNewMonitor.log)

**Comment by lwtnb-wrk** [comment]
@AlencarGabriel Favor atualizar para a ultima versão do Monitor Electron e efetuar novos testes.
Caso o problema persista reabra o chamado ou crie um novo.
