### ISSUE TITLE
Totvs Monitor - Lentidão

### ISSUE THREAD

**Issue by RegisNJr** [totvs/tds-monitor-standalone#9]
Atualmente utilizo os Appservers na Build19 e fui obrigado a usar o novo Totvs Monitor.
Temos 1 Master e 90 Slaves configurados que no Monitor antigo abria rapidamente.

Porém agora usando a mesma configuração de Master/Slave quando eu configuro o IP e Porta do Servidor Master para visualizar as conexões no Monitor é comum eu ter cerca de 1500/1600 conexões porém nesse novo Monitor na maioria das vezes fica extremamente lento, tem momento que fica carregando e não abre, tenho que finalizar tarefa e já aconteceu varias vezes de abrir novamente e perder todos servidores salvos.

Uso a seguinte versão: **TOTVS Monitor v0.1.4**
@totvs/tds-languageclient: 0.0.15
@totvs/tds-monitor-frontend: ^0.1.3

Vocês tem histórico desse tipo de problema?

**Comment by RegisNJr** [comment]
Nessa versão ainda esta acontecendo a lentidão... fica somente conectando.

![image](https://user-images.githubusercontent.com/68110738/92257107-0e013580-eeab-11ea-8267-65dfa72c666f.png)

**Comment by lwtnb-wrk** [comment]
@RegisNJr Poderia testar na ultima versão e reportar se a lentidão persiste?
